/** 标签中文名 */
export const TAG_LABELS: Record<string, string> = {
  mood_happy: "开心",
  mood_peaceful: "淡淡",
  mood_healing: "治愈",
  mood_romantic: "浪漫",
  mood_literary: "文艺",
  mood_humor: "搞怪",
  mood_emo: "emo",
  mood_reflective: "感慨",
  mood_energetic: "元气",
  mood_mysterious: "酷感",
  mood_cool: "酷",
  mood_cool_pose: "装酷",
  mood_nostalgia: "怀旧",
  mood_philosophy: "哲思",
  scene_daily: "日常",
  scene_travel: "旅行",
  scene_food: "美食",
  scene_selfie: "自拍",
  scene_pet: "宠物",
  scene_work: "工作",
  scene_study: "学习",
  scene_social: "聚会",
  scene_home: "居家",
  scene_nature: "自然",
  scene_night: "夜晚",
  scene_music: "音乐",
  scene_holiday: "节日",
  scene_universal: "氛围",
  scene_rainy: "雨天",
  scene_season_spring: "春天",
  scene_season_autumn_winter: "秋冬",
  scene_season_winter: "冬天",
  style_minimal: "短句",
  style_essay: "长文",
  style_emoji_heavy: "emoji",
  style_cn_en_mix: "中英",
  style_pure_cn: "纯中文",
  style_symbol_deco: "符号",
  style_quote: "金句",
  style_colloquial: "口语",
  style_abstract: "抽象",
  style_poetic: "诗意",
  purpose_share_life: "晒生活",
  purpose_show_mood: "表达心情",
  purpose_heal_self: "自我治愈",
  purpose_subtle_love: "暗戳表白",
  purpose_cool_pose: "装酷",
  purpose_humble_brag: "小得意",
  purpose_complain: "吐槽",
  purpose_record: "仪式感",
  purpose_interact: "互动",
  theme_happiness: "快乐",
  theme_love: "爱情",
  theme_friendship: "友情",
  theme_family: "亲情",
  theme_freedom: "自由",
  theme_growth: "成长",
  theme_season_spring: "春天",
  theme_season_autumn_winter: "秋冬",
  theme_rainy: "雨天",
  theme_sunny: "晴天",
  theme_night_mood: "夜色",
  theme_foodie: "美食",
  theme_pet: "宠物",
  theme_work_life: "职场",
  theme_travel_wander: "旅行",
  theme_self_love: "自爱",
  theme_nostalgia: "怀旧",
  theme_philosophy: "哲思",
  theme_music: "音乐",
  theme_nature: "自然",
  theme_romantic: "浪漫",
};

export { QUIZ_STEPS, QUIZ_PRESET_CARDS, QUIZ_RELATION_STEPS } from "./quizConfig";
export type { QuizPresetCard } from "./quizConfig";
export {
  getPurposeAnswerKey,
  getRelationStep,
  shouldShowRelationStep,
  QUIZ_RELATION_ANSWER_INDEX,
} from "./quizConfig";

/** AI 意图解析用：中文 → tag_id */
export const CN_TO_TAG: Record<string, string> = {
  开心: "mood_happy",
  元气: "mood_energetic",
  快乐: "mood_happy",
  淡淡: "mood_peaceful",
  平静: "mood_peaceful",
  治愈: "mood_healing",
  温暖: "mood_healing",
  浪漫: "mood_romantic",
  心动: "mood_romantic",
  文艺: "mood_literary",
  感慨: "mood_reflective",
  搞怪: "mood_humor",
  幽默: "mood_humor",
  抽象: "style_abstract",
  emo: "mood_emo",
  丧: "mood_emo",
  酷: "mood_mysterious",
  疏离: "mood_mysterious",
  怀旧: "mood_nostalgia",
  哲思: "mood_philosophy",
  日常: "scene_daily",
  氛围: "scene_universal",
  通用: "scene_universal",
  旅行: "scene_travel",
  出游: "scene_travel",
  美食: "scene_food",
  探店: "scene_food",
  自拍: "scene_selfie",
  颜值: "scene_selfie",
  宠物: "scene_pet",
  猫: "scene_pet",
  狗: "scene_pet",
  工作: "scene_work",
  职场: "scene_work",
  加班: "scene_work",
  学习: "scene_study",
  校园: "scene_study",
  聚会: "scene_social",
  朋友: "scene_social",
  居家: "scene_home",
  家人: "scene_home",
  自然: "scene_nature",
  夏天: "scene_nature",
  夜晚: "scene_night",
  深夜: "scene_night",
  音乐: "scene_music",
  歌曲: "scene_music",
  节日: "scene_holiday",
  庆典: "scene_holiday",
  雨天: "scene_rainy",
  下雨: "scene_rainy",
  春天: "scene_season_spring",
  秋天: "scene_season_autumn_winter",
  冬天: "scene_season_winter",
  短句: "style_minimal",
  极简: "style_minimal",
  长文: "style_essay",
  长一点: "style_essay",
  emoji: "style_emoji_heavy",
  中英: "style_cn_en_mix",
  英文: "style_cn_en_mix",
  纯中文: "style_pure_cn",
  口语: "style_colloquial",
  接地气: "style_colloquial",
  诗意: "style_poetic",
  符号: "style_symbol_deco",
  颜文字: "style_symbol_deco",
  金句: "style_quote",
  引语: "style_quote",
  仪式感: "purpose_record",
  记录: "purpose_record",
  互动: "purpose_interact",
  分手: "theme_love",
  爱情: "theme_love",
};

export function formatTagLabels(tags: CopyTagsLike): string {
  const parts: string[] = [];
  const mood = tags.mood?.[0];
  const scene = tags.scene?.[0];
  if (mood && TAG_LABELS[mood]) parts.push(TAG_LABELS[mood]);
  if (scene && TAG_LABELS[scene]) parts.push(TAG_LABELS[scene]);
  return parts.join(" · ") || "氛围";
}

interface CopyTagsLike {
  mood?: string[];
  scene?: string[];
}
